# Generated by Django 5.1 on 2024-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_published",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Признак публичности"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="nice_habit",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Это привычка, которую можно привязать к выполнению полезной привычки?",
                null=True,
                verbose_name="Признак приятной привычки",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.DurationField(
                blank=True,
                default=1,
                help_text="Укажите периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Установите время, когда необходимо выполнять привычку",
                null=True,
                verbose_name="Время",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время на выполнение"
            ),
        ),
    ]
