# Generated by Django 5.1 on 2024-08-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_is_published_alter_habit_nice_habit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="associted_habit",
            new_name="associated_habit",
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                blank=True,
                help_text="Укажите периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
