# Generated by Django 5.1 on 2024-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                blank=True,
                default=1,
                help_text="Укажите периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)",
                null=True,
                verbose_name="Периодичность",
            ),
        ),
    ]
