# Generated by Django 5.1 on 2024-08-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_alter_habit_periodicity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="associated_habit",
            new_name="associted_habit",
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки для напоминания в днях (по умолчанию ежедневная)",
                verbose_name="Периодичность",
            ),
        ),
    ]
